#!/bin/bash

source ./mymkr.env
test -z "$MYMKR_PREFIX" && echo "MYMKR_PREFIX is not set" && exit 1
test ! -d $MYMKR_PREFIX && mkdir $MYMKR_PREFIX

JOBS='-j8'

########################################################################
# helper functions
########################################################################

color_black='\E[30m'
color_red='\E[31m'
color_green='\E[32m'
color_yellow='\E[33m'
color_blue='\E[34m'
color_magenta='\E[35m'
color_cyan='\E[36m'
color_white='\E[37m'
color_off='\E[0m'

notice () {
	echo -e "${color_green}[MYMKR NOTICE]${color_off} ${@}"
}

die () {
	echo -e "${color_red}[MYMKR ERROR]${color_off} ${@}"
	exit 1
}

########################################################################

case $1 in
	*)
		echo "USAGE: $0 <package>"
		echo -e "<package> is one of:"
		echo -e "\tclean   (cleans build related files)"
		#for x in $PKGS; do echo -e "\t$x"; done
		echo ':TODO: list pkgs n stuff'
		exit 1
		;;
esac

exit 0
